services:
  sdc-iron-web-1:
    build:
      context: .
      dockerfile: Dockerfile.ubuntu
    container_name: sdc-iron-web-1
    hostname: sdc-iron-web-1
    privileged: true
    cgroup: host
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - ./ssh-keys/authorized_keys:/home/cadet/.ssh/authorized_keys:ro
    networks:
      iron_net:
        ipv4_address: 172.36.0.11
    ports:
      - "2281:22"

  sdc-iron-web-2:
    build:
      context: .
      dockerfile: Dockerfile.ubuntu
    container_name: sdc-iron-web-2
    hostname: sdc-iron-web-2
    privileged: true
    cgroup: host
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - ./ssh-keys/authorized_keys:/home/cadet/.ssh/authorized_keys:ro
    networks:
      iron_net:
        ipv4_address: 172.36.0.12
    ports:
      - "2282:22"

  sdc-iron-db-1:
    build:
      context: .
      dockerfile: Dockerfile.rocky
    container_name: sdc-iron-db-1
    hostname: sdc-iron-db-1
    privileged: true
    cgroup: host
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - ./ssh-keys/authorized_keys:/home/cadet/.ssh/authorized_keys:ro
    networks:
      iron_net:
        ipv4_address: 172.36.0.13
    ports:
      - "2283:22"

  sdc-iron-db-2:
    build:
      context: .
      dockerfile: Dockerfile.rocky
    container_name: sdc-iron-db-2
    hostname: sdc-iron-db-2
    privileged: true
    cgroup: host
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - ./ssh-keys/authorized_keys:/home/cadet/.ssh/authorized_keys:ro
    networks:
      iron_net:
        ipv4_address: 172.36.0.14
    ports:
      - "2284:22"

  sdc-iron-app:
    build:
      context: .
      dockerfile: Dockerfile.ubuntu
    container_name: sdc-iron-app
    hostname: sdc-iron-app
    privileged: true
    cgroup: host
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - ./ssh-keys/authorized_keys:/home/cadet/.ssh/authorized_keys:ro
    networks:
      iron_net:
        ipv4_address: 172.36.0.15
    ports:
      - "2285:22"

  sdc-iron-comms:
    build:
      context: .
      dockerfile: Dockerfile.ubuntu
    container_name: sdc-iron-comms
    hostname: sdc-iron-comms
    privileged: true
    cgroup: host
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - ./ssh-keys/authorized_keys:/home/cadet/.ssh/authorized_keys:ro
    networks:
      iron_net:
        ipv4_address: 172.36.0.16
    ports:
      - "2286:22"

networks:
  iron_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.36.0.0/24
